"""add unique constraint for day obs seq num key

Revision ID: 67319407b5fc
Revises: bf7ed261cc12
Create Date: 2024-09-16 17:31:24.124147+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "67319407b5fc"
down_revision: Union[str, None] = "bf7ed261cc12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "un_exposure_flexdata_day_obs_seq_num_key",
        "exposure_flexdata",
        ["day_obs", "seq_num", "key"],
        schema="cdb_lsstcomcam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "un_exposure_flexdata_day_obs_seq_num_key",
        "exposure_flexdata",
        schema="cdb_lsstcomcam",
        type_="unique",
    )
    # ### end Alembic commands ###
