"""Add column scheduler_note

Revision ID: 6e179aa84440
Revises: 913d10c6ed81
Create Date: 2025-05-13 16:23:56.376857+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6e179aa84440"
down_revision: Union[str, None] = "913d10c6ed81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        "ccdexposure",
        "Information from observatory systems about each detector (CCD) within each raw image taken",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "ccdexposure_camera",
        "Information from the Camera Control System about each detector (CCD) within each raw image taken",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "ccdexposure_flexdata",
        "Flexible key/value metadata about each detector (CCD) within each raw image taken; used for development and engineering purposes",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "ccdexposure_flexdata_schema",
        "Key names and value types used in the ccdexposure_flexdata table",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "ccdexposure_quicklook",
        "Information from Summit Rapid Analysis about each detector (CCD) within each raw image taken",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "ccdvisit1_quicklook",
        "Information from Summit Rapid Analysis about each detector (CCD) within each visit in visit system 1 (visit per exposure); describes detectors in processed visit images (or calibrated exposures)",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.add_column(
        "exposure",
        sa.Column(
            "scheduler_note",
            sa.VARCHAR(length=1024)
            .with_variant(mysql.VARCHAR(length=1024), "mysql")
            .with_variant(sa.VARCHAR(length=1024), "postgresql"),
            nullable=True,
            comment="A note indicating how or why the observation was chosen by the Feature Based Scheduler.",
        ),
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "exposure",
        "Information from observatory systems about each raw image taken",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "exposure_flexdata",
        "Flexible key/value metadata about each raw image taken; used for development and engineering purposes",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "exposure_flexdata_schema",
        "Key names and value types used in the exposure_flexdata table",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "exposure_quicklook",
        "Information from Summit Rapid Analysis about each raw image taken",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    op.create_table_comment(
        "visit1_quicklook",
        "Information from Summit Rapid Analysis about each visit in visit system 1 (visit per exposure); describes processed visit images (or calibrated exposures)",
        existing_comment=None,
        schema="cdb_lsstcomcam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        "visit1_quicklook",
        existing_comment="Information from Summit Rapid Analysis about each visit in visit system 1 (visit per exposure); describes processed visit images (or calibrated exposures)",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "exposure_quicklook",
        existing_comment="Information from Summit Rapid Analysis about each raw image taken",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "exposure_flexdata_schema",
        existing_comment="Key names and value types used in the exposure_flexdata table",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "exposure_flexdata",
        existing_comment="Flexible key/value metadata about each raw image taken; used for development and engineering purposes",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "exposure",
        existing_comment="Information from observatory systems about each raw image taken",
        schema="cdb_lsstcomcam",
    )
    op.drop_column("exposure", "scheduler_note", schema="cdb_lsstcomcam")
    op.drop_table_comment(
        "ccdvisit1_quicklook",
        existing_comment="Information from Summit Rapid Analysis about each detector (CCD) within each visit in visit system 1 (visit per exposure); describes detectors in processed visit images (or calibrated exposures)",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "ccdexposure_quicklook",
        existing_comment="Information from Summit Rapid Analysis about each detector (CCD) within each raw image taken",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "ccdexposure_flexdata_schema",
        existing_comment="Key names and value types used in the ccdexposure_flexdata table",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "ccdexposure_flexdata",
        existing_comment="Flexible key/value metadata about each detector (CCD) within each raw image taken; used for development and engineering purposes",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "ccdexposure_camera",
        existing_comment="Information from the Camera Control System about each detector (CCD) within each raw image taken",
        schema="cdb_lsstcomcam",
    )
    op.drop_table_comment(
        "ccdexposure",
        existing_comment="Information from observatory systems about each detector (CCD) within each raw image taken",
        schema="cdb_lsstcomcam",
    )
    # ### end Alembic commands ###
