"""Add astrometric RA and Dec to quicklook tables

Revision ID: 8aa6361ff307
Revises: b3bf526692dd
Create Date: 2026-01-30 15:03:37.017732+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8aa6361ff307"
down_revision: Union[str, None] = "b3bf526692dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ccdvisit1_quicklook", "s_dec", schema="cdb_lsstcomcam")
    op.drop_column("ccdvisit1_quicklook", "s_ra", schema="cdb_lsstcomcam")
    op.alter_column(
        "exposure",
        "s_ra",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Central Spatial Position in ICRS; right ascension of focal plane center derived from encoder readings and correcting for annual abberation, precession-nutation, earth orientation, atmospheric refraction, and mount/flexure model, determined without reference to a plate solution.",
        existing_comment="Central Spatial Position in ICRS; Right ascension of targeted focal plane center.",
        existing_nullable=True,
        schema="cdb_lsstcomcam",
    )
    op.alter_column(
        "exposure",
        "s_dec",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Central Spatial Position in ICRS; declination of focal plane center derived from encoder readings and correcting for annual abberation, precession-nutation, earth orientation, atmospheric refraction, and mount/flexure model, determined without reference to a plate solution.",
        existing_comment="Central Spatial Position in ICRS; Declination of targeted focal plane center.",
        existing_nullable=True,
        schema="cdb_lsstcomcam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "exposure",
        "s_dec",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Central Spatial Position in ICRS; Declination of targeted focal plane center.",
        existing_comment="Central Spatial Position in ICRS; declination of focal plane center derived from encoder readings and correcting for annual abberation, precession-nutation, earth orientation, atmospheric refraction, and mount/flexure model, determined without reference to a plate solution.",
        existing_nullable=True,
        schema="cdb_lsstcomcam",
    )
    op.alter_column(
        "exposure",
        "s_ra",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Central Spatial Position in ICRS; Right ascension of targeted focal plane center.",
        existing_comment="Central Spatial Position in ICRS; right ascension of focal plane center derived from encoder readings and correcting for annual abberation, precession-nutation, earth orientation, atmospheric refraction, and mount/flexure model, determined without reference to a plate solution.",
        existing_nullable=True,
        schema="cdb_lsstcomcam",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "s_ra",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Central Spatial Position in ICRS; Computed right ascension of CCD center.",
        ),
        schema="cdb_lsstcomcam",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "s_dec",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Central Spatial Position in ICRS; Computed declination of CCD center.",
        ),
        schema="cdb_lsstcomcam",
    )
    # ### end Alembic commands ###
