"""Fix visit_id in ccdvisit views.

Revision ID: 913d10c6ed81
Revises: 12f0d22a2347
Create Date: 2024-12-05 00:56:53.875464+00:00

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "913d10c6ed81"
down_revision: Union[str, None] = "12f0d22a2347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE cdb_latiss.ccdvisit1 RENAME COLUMN exposure_id TO visit_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE cdb_latiss.ccdvisit1 RENAME COLUMN visit_id TO exposure_id")
    # ### end Alembic commands ###
