"""Revise table relationships

Revision ID: 68d56f535626
Revises: 42cf2352803d
Create Date: 2026-01-04 00:09:57.372258+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68d56f535626"
down_revision: Union[str, None] = "42cf2352803d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "un_exposure_exposure_id_day_obs_seq_num",
        "exposure",
        ["exposure_id", "day_obs", "seq_num"],
        schema="cdb_lsstcomcamsim",
    )
    op.create_unique_constraint(
        "un_ccdexposure_ccdexposure_id_day_obs_seq_num_detector",
        "ccdexposure",
        ["ccdexposure_id", "day_obs", "seq_num", "detector"],
        schema="cdb_lsstcomcamsim",
    )
    op.create_table(
        "exposure_quicklook",
        sa.Column(
            "exposure_id",
            sa.BIGINT().with_variant(mysql.BIGINT(), "mysql").with_variant(sa.BIGINT(), "postgresql"),
            nullable=False,
            comment="Unique identifier.",
        ),
        sa.Column(
            "day_obs",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="Day of observation.",
        ),
        sa.Column(
            "seq_num",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="Sequence number.",
        ),
        sa.Column(
            "postisr_pixel_median_median",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Median postISR pixel value (median across all detectors).",
        ),
        sa.Column(
            "postisr_pixel_median_mean",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Median postISR pixel value (mean across all detectors).",
        ),
        sa.Column(
            "postisr_pixel_median_max",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Median postISR pixel value (max across all detectors).",
        ),
        sa.Column(
            "mount_motion_image_degradation",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Image degradation due to mount motion.",
        ),
        sa.Column(
            "mount_motion_image_degradation_az",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Image degradation due to mount motion in azimuth.",
        ),
        sa.Column(
            "mount_motion_image_degradation_el",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Image degradation due to mount motion in elevation.",
        ),
        sa.Column(
            "mount_motion_image_degradation_rot",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Image degradation due to rotator jitter.",
        ),
        sa.Column(
            "mount_jitter_rms_cam_hexapod",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="The RMS image motion due to movement of the camera hexapod.",
        ),
        sa.Column(
            "mount_jitter_rms_m2_hexapod",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="The RMS image motion due to movement of the M2 hexapod.",
        ),
        sa.Column(
            "mount_jitter_rms",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="RMS mount jitter.",
        ),
        sa.Column(
            "mount_jitter_rms_az",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Azimuth RMS mount jitter.",
        ),
        sa.Column(
            "mount_jitter_rms_el",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Elevation RMS mount jitter.",
        ),
        sa.Column(
            "mount_jitter_rms_rot",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Rotator RMS mount jitter.",
        ),
        sa.ForeignKeyConstraint(
            ["day_obs", "seq_num"],
            ["cdb_lsstcomcamsim.exposure.day_obs", "cdb_lsstcomcamsim.exposure.seq_num"],
            name="fk_exposure_quicklook_day_obs_seq_num",
        ),
        sa.ForeignKeyConstraint(
            ["exposure_id", "day_obs", "seq_num"],
            [
                "cdb_lsstcomcamsim.exposure.exposure_id",
                "cdb_lsstcomcamsim.exposure.day_obs",
                "cdb_lsstcomcamsim.exposure.seq_num",
            ],
            name="fk_exposure_quicklook_exposure_id_day_obs_seq_num",
        ),
        sa.ForeignKeyConstraint(
            ["exposure_id"], ["cdb_lsstcomcamsim.exposure.exposure_id"], name="fk_exposure_quicklook_obs_id"
        ),
        sa.PrimaryKeyConstraint("day_obs", "seq_num"),
        schema="cdb_lsstcomcamsim",
        comment="Information from Summit Rapid Analysis about each raw image taken",
        mysql_engine="MyISAM",
    )
    op.drop_constraint(
        op.f("un_ccdexposure_day_obs_seq_num_detector"),
        "ccdexposure",
        schema="cdb_lsstcomcamsim",
        type_="unique",
    )
    op.drop_constraint(
        "un_ccdexposure_ccdexposure_id", "ccdexposure", schema="cdb_lsstcomcamsim", type_="unique"
    )
    op.drop_constraint(
        "fk_ccdexposure_id", "ccdexposure_camera", schema="cdb_lsstcomcamsim", type_="foreignkey"
    )
    op.drop_constraint("fk_obs_id", "ccdexposure_flexdata", schema="cdb_lsstcomcamsim", type_="foreignkey")
    op.drop_constraint("fk_obs_id", "ccdvisit1_quicklook", schema="cdb_lsstcomcamsim", type_="foreignkey")
    op.drop_constraint(
        "fk_ccdexposure_exposure_id", "ccdexposure", schema="cdb_lsstcomcamsim", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_exposure_flexdata_obs_id", "exposure_flexdata", schema="cdb_lsstcomcamsim", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_exposure_quicklook_obs_id", "exposure_quicklook", schema="cdb_lsstcomcamsim", type_="foreignkey"
    )
    op.drop_constraint("fk_obs_id", "visit1_quicklook", schema="cdb_lsstcomcamsim", type_="foreignkey")
    op.drop_constraint("exposure_pkey", "exposure", schema="cdb_lsstcomcamsim", type_="primary")
    op.drop_constraint("ccdexposure_pkey", "ccdexposure", schema="cdb_lsstcomcamsim", type_="primary")
    op.create_unique_constraint(
        "un_ccdexposure_ccdexposure_id", "ccdexposure", ["ccdexposure_id"], schema="cdb_lsstcomcamsim"
    )
    op.create_primary_key(
        "un_ccdexposure_day_obs_seq_num_detector",
        "ccdexposure",
        ["day_obs", "seq_num", "detector"],
        schema="cdb_lsstcomcamsim",
    )
    op.create_table(
        "ccdexposure_quicklook",
        sa.Column(
            "day_obs",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="Day of observation.",
        ),
        sa.Column(
            "seq_num",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="Sequence number.",
        ),
        sa.Column(
            "detector",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=False,
            comment="Number of the detector in the focal plane.",
        ),
        sa.Column(
            "ccdexposure_id",
            sa.BIGINT().with_variant(mysql.BIGINT(), "mysql").with_variant(sa.BIGINT(), "postgresql"),
            nullable=False,
            comment="Unique identifier.",
        ),
        sa.Column(
            "postisr_pixel_median",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Median postISR pixel value.",
        ),
        sa.ForeignKeyConstraint(
            ["ccdexposure_id", "day_obs", "seq_num", "detector"],
            [
                "cdb_lsstcomcamsim.ccdexposure.ccdexposure_id",
                "cdb_lsstcomcamsim.ccdexposure.day_obs",
                "cdb_lsstcomcamsim.ccdexposure.seq_num",
                "cdb_lsstcomcamsim.ccdexposure.detector",
            ],
            name="fk_ccdexposure_qk_id_day_seq_det",
        ),
        sa.ForeignKeyConstraint(
            ["ccdexposure_id"],
            ["cdb_lsstcomcamsim.ccdexposure.ccdexposure_id"],
            name="fk_ccdexposure_quicklook_obs_id",
        ),
        sa.ForeignKeyConstraint(
            ["day_obs", "seq_num", "detector"],
            [
                "cdb_lsstcomcamsim.ccdexposure.day_obs",
                "cdb_lsstcomcamsim.ccdexposure.seq_num",
                "cdb_lsstcomcamsim.ccdexposure.detector",
            ],
            name="fk_ccdexposure_quicklook_day_obs_seq_num_detector",
        ),
        sa.PrimaryKeyConstraint("day_obs", "seq_num", "detector"),
        schema="cdb_lsstcomcamsim",
        comment="Information from Summit Rapid Analysis about each detector (CCD) within each raw image taken",
        mysql_engine="MyISAM",
    )
    op.create_foreign_key(
        "fk_ccdexposure_exposure_id_day_obs_seq_num",
        "ccdexposure",
        "exposure",
        ["exposure_id", "day_obs", "seq_num"],
        ["exposure_id", "day_obs", "seq_num"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdexposure_camera_ccdexposure_id",
        "ccdexposure_camera",
        "ccdexposure",
        ["ccdexposure_id"],
        ["ccdexposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdexposure_camera",
        sa.Column(
            "day_obs",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Day of observation.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdexposure_camera",
        sa.Column(
            "seq_num",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Sequence number.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdexposure_camera",
        sa.Column(
            "detector",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Number of the detector in the focal plane.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.execute(
        """
        UPDATE cdb_lsstcomcamsim.ccdexposure_camera SET
            day_obs = (
                SELECT day_obs
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdexposure_camera.ccdexposure_id
            ),
            seq_num = (
                SELECT seq_num
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdexposure_camera.ccdexposure_id
            ),
            detector = (
                SELECT detector
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdexposure_camera.ccdexposure_id
            )
        """
    )
    op.alter_column(
        "ccdexposure_camera",
        "day_obs",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.alter_column(
        "ccdexposure_camera",
        "seq_num",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.alter_column(
        "ccdexposure_camera",
        "detector",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdexposure_camera_day_obs_seq_num_detector",
        "ccdexposure_camera",
        "ccdexposure",
        ["day_obs", "seq_num", "detector"],
        ["day_obs", "seq_num", "detector"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdexposure_camera_ccdexposure_id_day_obs_seq_num_detector",
        "ccdexposure_camera",
        "ccdexposure",
        ["ccdexposure_id", "day_obs", "seq_num", "detector"],
        ["ccdexposure_id", "day_obs", "seq_num", "detector"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdexposure_flexdata",
        sa.Column(
            "day_obs",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Day of observation.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdexposure_flexdata",
        sa.Column(
            "seq_num",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Sequence number.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdexposure_flexdata",
        sa.Column(
            "detector",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Number of the detector in the focal plane.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdexposure_flexdata_obs_id",
        "ccdexposure_flexdata",
        "ccdexposure",
        ["obs_id"],
        ["ccdexposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.execute(
        """
        UPDATE cdb_lsstcomcamsim.ccdexposure_flexdata SET
            day_obs = (
                SELECT day_obs
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdexposure_flexdata.obs_id
            ),
            seq_num = (
                SELECT seq_num
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdexposure_flexdata.obs_id
            ),
            detector = (
                SELECT detector
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdexposure_flexdata.obs_id
            )
        """
    )
    op.alter_column(
        "ccdexposure_flexdata",
        "day_obs",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.alter_column(
        "ccdexposure_flexdata",
        "seq_num",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.alter_column(
        "ccdexposure_flexdata",
        "detector",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdexposure_flexdata_day_obs_seq_num_detector",
        "ccdexposure_flexdata",
        "ccdexposure",
        ["day_obs", "seq_num", "detector"],
        ["day_obs", "seq_num", "detector"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdexposure_flexdata_obs_id_day_obs_seq_num_detector",
        "ccdexposure_flexdata",
        "ccdexposure",
        ["obs_id", "day_obs", "seq_num", "detector"],
        ["ccdexposure_id", "day_obs", "seq_num", "detector"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "day_obs",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Day of observation.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "seq_num",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Sequence number.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "detector",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Number of the detector in the focal plane.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdvisit1_quicklook_obs_id",
        "ccdvisit1_quicklook",
        "ccdexposure",
        ["ccdvisit_id"],
        ["ccdexposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.execute(
        """
        UPDATE cdb_lsstcomcamsim.ccdvisit1_quicklook SET
            day_obs = (
                SELECT day_obs
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdvisit1_quicklook.ccdvisit_id
            ),
            seq_num = (
                SELECT seq_num
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdvisit1_quicklook.ccdvisit_id
            ),
            detector = (
                SELECT detector
                FROM cdb_lsstcomcamsim.ccdexposure
                WHERE cdb_lsstcomcamsim.ccdexposure.ccdexposure_id = cdb_lsstcomcamsim.ccdvisit1_quicklook.ccdvisit_id
            )
        """
    )
    op.alter_column(
        "ccdvisit1_quicklook",
        "day_obs",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.alter_column(
        "ccdvisit1_quicklook",
        "seq_num",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.alter_column(
        "ccdvisit1_quicklook",
        "detector",
        existing_type=sa.INTEGER()
        .with_variant(mysql.INTEGER(), "mysql")
        .with_variant(sa.INTEGER(), "postgresql"),
        nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdvisit1_quicklook_day_obs_seq_num_detector",
        "ccdvisit1_quicklook",
        "ccdexposure",
        ["day_obs", "seq_num", "detector"],
        ["day_obs", "seq_num", "detector"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdvisit1_quicklook_ccdvisit_id_day_obs_seq_num_detector",
        "ccdvisit1_quicklook",
        "ccdexposure",
        ["ccdvisit_id", "day_obs", "seq_num", "detector"],
        ["ccdexposure_id", "day_obs", "seq_num", "detector"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.drop_column("ccdvisit1_quicklook", "postisr_pixel_median", schema="cdb_lsstcomcamsim")
    op.create_unique_constraint(
        "un_exposure_flexdata_obs_id_key", "exposure_flexdata", ["obs_id", "key"], schema="cdb_lsstcomcamsim"
    )
    op.create_foreign_key(
        "fk_exposure_flexdata_obs_id_day_obs_seq_num",
        "exposure_flexdata",
        "exposure",
        ["obs_id", "day_obs", "seq_num"],
        ["exposure_id", "day_obs", "seq_num"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_visit1_quicklook_visit_id_day_obs_seq_num",
        "visit1_quicklook",
        "exposure",
        ["visit_id", "day_obs", "seq_num"],
        ["exposure_id", "day_obs", "seq_num"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint(
        "ccdexposure_camera_pkey", "ccdexposure_camera", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "ccdexposure_camera_pkey",
        "ccdexposure_camera",
        ["day_obs", "seq_num", "detector"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint(
        "ccdexposure_flexdata_pkey", "ccdexposure_flexdata", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "ccdexposure_flexdata_pkey",
        "ccdexposure_flexdata",
        ["day_obs", "seq_num", "detector", "key"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint(
        "ccdvisit1_quicklook_pkey", "ccdvisit1_quicklook", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "ccdvisit1_quicklook_pkey",
        "ccdvisit1_quicklook",
        ["day_obs", "seq_num", "detector"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint(
        "visit1_quicklook_pkey", "visit1_quicklook", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "visit1_quicklook_pkey",
        "visit1_quicklook",
        ["day_obs", "seq_num"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint(
        "exposure_flexdata_pkey", "exposure_flexdata", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "exposure_flexdata_pkey",
        "exposure_flexdata",
        ["day_obs", "seq_num", "key"],
        schema="cdb_lsstcomcamsim",
    )
    op.create_primary_key("exposure_pkey", "exposure", ["day_obs", "seq_num"], schema="cdb_lsstcomcamsim")
    op.create_foreign_key(
        "fk_ccdexposure_exposure_id",
        "ccdexposure",
        "exposure",
        ["exposure_id"],
        ["exposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_exposure_flexdata_obs_id",
        "exposure_flexdata",
        "exposure",
        ["obs_id"],
        ["exposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_exposure_quicklook_obs_id",
        "exposure_quicklook",
        "exposure",
        ["exposure_id"],
        ["exposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_visit1_quicklook_obs_id",
        "visit1_quicklook",
        "exposure",
        ["visit_id"],
        ["exposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_visit1_quicklook_obs_id", "visit1_quicklook", schema="cdb_lsstcomcamsim", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_exposure_quicklook_obs_id", "exposure_quicklook", schema="cdb_lsstcomcamsim", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_exposure_flexdata_obs_id", "exposure_flexdata", schema="cdb_lsstcomcamsim", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_ccdexposure_exposure_id", "ccdexposure", schema="cdb_lsstcomcamsim", type_="foreignkey"
    )
    op.drop_table("ccdexposure_quicklook", schema="cdb_lsstcomcamsim")
    op.drop_table("exposure_quicklook", schema="cdb_lsstcomcamsim")
    op.drop_constraint(
        "fk_ccdexposure_exposure_id_day_obs_seq_num",
        "ccdexposure",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_visit1_quicklook_visit_id_day_obs_seq_num",
        "visit1_quicklook",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "visit1_quicklook_pkey", "visit1_quicklook", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "visit1_quicklook_pkey",
        "visit1_quicklook",
        ["visit_id"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint(
        "fk_exposure_flexdata_obs_id_day_obs_seq_num",
        "exposure_flexdata",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "un_exposure_flexdata_obs_id_key", "exposure_flexdata", schema="cdb_lsstcomcamsim", type_="unique"
    )
    op.drop_constraint(
        "un_exposure_exposure_id_day_obs_seq_num", "exposure", schema="cdb_lsstcomcamsim", type_="unique"
    )
    op.alter_column(
        "exposure",
        "exposure_id",
        existing_type=sa.BIGINT()
        .with_variant(mysql.BIGINT(), "mysql")
        .with_variant(sa.BIGINT(), "postgresql"),
        server_default=None,
        existing_nullable=False,
        schema="cdb_lsstcomcamsim",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "postisr_pixel_median",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Median postISR pixel value.",
        ),
        schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint(
        "fk_ccdvisit1_quicklook_ccdvisit_id_day_obs_seq_num_detector",
        "ccdvisit1_quicklook",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_ccdvisit1_quicklook_obs_id",
        "ccdvisit1_quicklook",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_ccdvisit1_quicklook_day_obs_seq_num_detector",
        "ccdvisit1_quicklook",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "ccdvisit1_quicklook_pkey", "ccdvisit1_quicklook", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "ccdvisit1_quicklook_pkey",
        "ccdvisit1_quicklook",
        ["ccdvisit_id"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_column("ccdvisit1_quicklook", "detector", schema="cdb_lsstcomcamsim")
    op.drop_column("ccdvisit1_quicklook", "seq_num", schema="cdb_lsstcomcamsim")
    op.drop_column("ccdvisit1_quicklook", "day_obs", schema="cdb_lsstcomcamsim")
    op.drop_constraint(
        "fk_ccdexposure_flexdata_obs_id_day_obs_seq_num_detector",
        "ccdexposure_flexdata",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_ccdexposure_flexdata_obs_id",
        "ccdexposure_flexdata",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_ccdexposure_flexdata_day_obs_seq_num_detector",
        "ccdexposure_flexdata",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "ccdexposure_flexdata_pkey", "ccdexposure_flexdata", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "ccdexposure_flexdata_pkey",
        "ccdexposure_flexdata",
        ["obs_id", "key"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_column("ccdexposure_flexdata", "detector", schema="cdb_lsstcomcamsim")
    op.drop_column("ccdexposure_flexdata", "seq_num", schema="cdb_lsstcomcamsim")
    op.drop_column("ccdexposure_flexdata", "day_obs", schema="cdb_lsstcomcamsim")
    op.drop_constraint(
        "fk_ccdexposure_camera_ccdexposure_id_day_obs_seq_num_detector",
        "ccdexposure_camera",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "ccdexposure_camera_pkey", "ccdexposure_camera", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "ccdexposure_camera_pkey",
        "ccdexposure_camera",
        ["ccdexposure_id"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint(
        "fk_ccdexposure_camera_ccdexposure_id",
        "ccdexposure_camera",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_ccdexposure_camera_day_obs_seq_num_detector",
        "ccdexposure_camera",
        schema="cdb_lsstcomcamsim",
        type_="foreignkey",
    )
    op.drop_column("ccdexposure_camera", "detector", schema="cdb_lsstcomcamsim")
    op.drop_column("ccdexposure_camera", "seq_num", schema="cdb_lsstcomcamsim")
    op.drop_column("ccdexposure_camera", "day_obs", schema="cdb_lsstcomcamsim")
    op.drop_constraint(
        "un_ccdexposure_ccdexposure_id_day_obs_seq_num_detector",
        "ccdexposure",
        schema="cdb_lsstcomcamsim",
        type_="unique",
    )
    op.drop_constraint(
        "un_ccdexposure_day_obs_seq_num_detector",
        "ccdexposure",
        schema="cdb_lsstcomcamsim",
        type_="primary",
    )
    op.drop_constraint(
        "un_ccdexposure_ccdexposure_id", "ccdexposure", schema="cdb_lsstcomcamsim", type_="unique"
    )
    op.create_primary_key("ccdexposure_pkey", "ccdexposure", ["ccdexposure_id"], schema="cdb_lsstcomcamsim")
    op.create_unique_constraint(
        "un_ccdexposure_ccdexposure_id", "ccdexposure", ["ccdexposure_id"], schema="cdb_lsstcomcamsim"
    )
    op.create_unique_constraint(
        op.f("un_ccdexposure_day_obs_seq_num_detector"),
        "ccdexposure",
        ["day_obs", "seq_num", "detector"],
        schema="cdb_lsstcomcamsim",
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(
        "exposure_flexdata_pkey", "exposure_flexdata", schema="cdb_lsstcomcamsim", type_="primary"
    )
    op.create_primary_key(
        "exposure_flexdata_pkey",
        "exposure_flexdata",
        ["obs_id", "key"],
        schema="cdb_lsstcomcamsim",
    )
    op.drop_constraint("exposure_pkey", "exposure", schema="cdb_lsstcomcamsim", type_="primary")
    op.create_primary_key("exposure_pkey", "exposure", ["exposure_id"], schema="cdb_lsstcomcamsim")
    op.create_foreign_key(
        "fk_ccdexposure_exposure_id",
        "ccdexposure",
        "exposure",
        ["exposure_id"],
        ["exposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_exposure_flexdata_obs_id",
        "exposure_flexdata",
        "exposure",
        ["obs_id"],
        ["exposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_ccdexposure_id",
        "ccdexposure_camera",
        "ccdexposure",
        ["ccdexposure_id"],
        ["ccdexposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_obs_id",
        "ccdexposure_flexdata",
        "ccdexposure",
        ["obs_id"],
        ["ccdexposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_obs_id",
        "ccdvisit1_quicklook",
        "ccdexposure",
        ["ccdvisit_id"],
        ["ccdexposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    op.create_foreign_key(
        "fk_obs_id",
        "visit1_quicklook",
        "exposure",
        ["visit_id"],
        ["exposure_id"],
        source_schema="cdb_lsstcomcamsim",
        referent_schema="cdb_lsstcomcamsim",
    )
    # ### end Alembic commands ###
