"""Restore single-column ID indexes dropped by multi-column primary keys

Revision ID: 8231272e261b
Revises: 1b33a651d8bb
Create Date: 2026-08-14 19:47:50.090246+00:00

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8231272e261b"
down_revision: str | None = "1b33a651d8bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_ccdexposure_camera_ccdexposure_id",
        "ccdexposure_camera",
        ["ccdexposure_id"],
        unique=False,
        schema="cdb_lsstcomcamsim",
    )
    op.create_index(
        "idx_ccdexposure_flexdata_obs_id_key",
        "ccdexposure_flexdata",
        ["obs_id", "key"],
        unique=False,
        schema="cdb_lsstcomcamsim",
    )
    op.create_index(
        "idx_ccdexposure_quicklook_ccdexposure_id",
        "ccdexposure_quicklook",
        ["ccdexposure_id"],
        unique=False,
        schema="cdb_lsstcomcamsim",
    )
    op.create_index(
        "idx_ccdvisit1_quicklook_ccdvisit_id",
        "ccdvisit1_quicklook",
        ["ccdvisit_id"],
        unique=False,
        schema="cdb_lsstcomcamsim",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_ccdvisit1_quicklook_ccdvisit_id", table_name="ccdvisit1_quicklook", schema="cdb_lsstcomcamsim"
    )
    op.drop_index(
        "idx_ccdexposure_quicklook_ccdexposure_id",
        table_name="ccdexposure_quicklook",
        schema="cdb_lsstcomcamsim",
    )
    op.drop_index(
        "idx_ccdexposure_flexdata_obs_id_key", table_name="ccdexposure_flexdata", schema="cdb_lsstcomcamsim"
    )
    op.drop_index(
        "idx_ccdexposure_camera_ccdexposure_id", table_name="ccdexposure_camera", schema="cdb_lsstcomcamsim"
    )
    # ### end Alembic commands ###
