"""Add column scheduler_note to exposure

Revision ID: d928dc20a5e0
Revises: 8024a0becf41
Create Date: 2025-05-14 16:05:06.656456+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d928dc20a5e0"
down_revision: Union[str, None] = "8024a0becf41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exposure",
        sa.Column(
            "scheduler_note",
            sa.VARCHAR(length=1024)
            .with_variant(mysql.VARCHAR(length=1024), "mysql")
            .with_variant(sa.VARCHAR(length=1024), "postgresql"),
            nullable=True,
            comment="A note indicating how or why the observation was chosen by the Feature Based Scheduler.",
        ),
        schema="cdb_lsstcomcamsim",
    )

    op.execute("DROP VIEW cdb_lsstcomcamsim.ccdvisit1")
    op.execute("DROP VIEW cdb_lsstcomcamsim.visit1")
    op.execute("CREATE VIEW cdb_lsstcomcamsim.ccdvisit1 AS SELECT * FROM cdb_lsstcomcamsim.ccdexposure")
    op.execute("CREATE VIEW cdb_lsstcomcamsim.visit1 AS SELECT * FROM cdb_lsstcomcamsim.exposure")
    op.execute("ALTER TABLE cdb_lsstcomcamsim.ccdvisit1 RENAME COLUMN ccdexposure_id TO ccdvisit_id")
    op.execute("ALTER TABLE cdb_lsstcomcamsim.ccdvisit1 RENAME COLUMN exposure_id TO visit_id")
    op.execute("ALTER TABLE cdb_lsstcomcamsim.visit1 RENAME COLUMN exposure_id TO visit_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exposure", "scheduler_note", schema="cdb_lsstcomcamsim")

    op.execute("DROP VIEW cdb_lsstcomcamsim.ccdvisit1")
    op.execute("DROP VIEW cdb_lsstcomcamsim.visit1")
    op.execute("CREATE VIEW cdb_lsstcomcamsim.ccdvisit1 AS SELECT * FROM cdb_lsstcomcamsim.ccdexposure")
    op.execute("CREATE VIEW cdb_lsstcomcamsim.visit1 AS SELECT * FROM cdb_lsstcomcamsim.exposure")
    op.execute("ALTER TABLE cdb_lsstcomcamsim.ccdvisit1 RENAME COLUMN ccdexposure_id TO ccdvisit_id")
    op.execute("ALTER TABLE cdb_lsstcomcamsim.ccdvisit1 RENAME COLUMN exposure_id TO visit_id")
    op.execute("ALTER TABLE cdb_lsstcomcamsim.visit1 RENAME COLUMN exposure_id TO visit_id")
    # ### end Alembic commands ###
