#!/usr/bin/env python

#
# How to use this script:
# 1. Install required packages and sdm_schemas, set environment variables:
#        pip install lsst-felis testing.postgresql alembic sqlalchemy pyyaml \
#           black psycopg2-binary
#        git clone https://github.com/lsst/sdm_schemas
#        cd sdm_schemas
#        export SDM_SCHEMAS_DIR=`pwd```
# 2. From the root of the consdb git repo, invoke the script. Supply a
#    revision message as the command line argument:
#        python alembic-autogenerate.py this is my revision message "\n" \
#            the message can span multiple lines "\n" \
#            if desired
# 3. Revise your auto-generated code as needed.
# 4. Remove the autogenerated creation of sql views (visit1, ccdvisit1).
#

import argparse
import os
import sys
import subprocess
from pathlib import Path

from felis.tests.postgresql import setup_postgres_test_db
from sqlalchemy.sql import text

parser = argparse.ArgumentParser(description="Generate Alembic migrations for ConsDB.")
parser.add_argument(
    "--instrument",
    help="Generate migrations only for the specified instrument (default: all).",
)
parser.add_argument("message", nargs=argparse.REMAINDER, help="Revision message.")
args = parser.parse_args()

if not args.message:
    print(
        f"""
    Usage:
        {sys.argv[0]} [--instrument INSTRUMENT] put a revision message here

    """
    )
    sys.exit(1)

revision_message = " ".join(args.message)

# Configuration for Alembic
alembic_ini_path = "alembic.ini"


def run(cmd, env=None):
    print("+", " ".join(cmd))
    subprocess.run(cmd, check=True, env=env)


sdm_schemas_dir = os.environ["SDM_SCHEMAS_DIR"]
schemas_dir = Path(sdm_schemas_dir) / "yml"

if args.instrument:
    instruments = [args.instrument]
else:
    instruments = ["latiss", "lsstcomcam", "lsstcomcamsim", "lsstcam"]

# Loop over each of the instruments
for instrument in instruments:
    # Set up a temporary PostgreSQL instance using testing.postgresql
    with setup_postgres_test_db() as instance:
        db_url = instance.url
        env = os.environ.copy()
        env["CONSDB_URL"] = db_url
        # Create schema
        with instance.engine.connect() as connection:
            connection.execute(text("CREATE EXTENSION IF NOT EXISTS pg_sphere;"))
            connection.execute(text("CREATE SCHEMA cdb;"))
            connection.execute(text(f"CREATE SCHEMA cdb_{instrument};"))
            connection.execute(text("CREATE USER usdf;"))
            connection.execute(text("CREATE USER oods;"))
            connection.commit()

        # Apply the HEAD schema to the database
        run(
            [
                "alembic",
                "-c",
                alembic_ini_path,
                "-n",
                instrument,
                "upgrade",
                "head",
            ],
            env=env,
        )

        # Autogenerate a new migration
        run(
            [
                "alembic",
                "-c",
                alembic_ini_path,
                "-n",
                instrument,
                "revision",
                "--autogenerate",
                "-m",
                revision_message,
            ],
            env=env,
        )

print(
    """
==========================================
 Don't forget to edit your migration files.
 You might need to shuffle data around
 to accommodate the new schema!
==========================================
"""
)
