FROM python:3.11
RUN pip install flask gunicorn sqlalchemy psycopg2
WORKDIR /consdb-pq
COPY python/lsst/consdb/pqserver.py python/lsst/consdb/utils.py /consdb-pq/
# Environment variables that must be set:
# DB_HOST DB_PASS DB_USER DB_NAME or POSTGRES_URL

# Expose the port.
EXPOSE 8080

ENTRYPOINT [ "gunicorn", "-b", "0.0.0.0:8080", "-w", "2", "pqserver:app" ]

