#!/usr/bin/env python3
"""
Validate Alembic migrations against SDM schema YAMLs.

The goal of this script is to establish the correctness of a freshly-authored
Alembic migration. A correct migration:

  * faithfully reflects the *target* SDM YAML, such that running it leaves the
    database matching the new schema, with no leftover divergence;
  * is reversible -- running it forward then back leaves the database matching
    the previous schema; and
  * is idempotent across repeated upgrade/downgrade cycles.

It does this in three stages:

1) **Autogenerate no-op check.** Run ``alembic-autogenerate.py`` against the
   current (post-migration) sdm_schemas. If the head migration is correct,
   re-running autogenerate against it should yield a migration whose
   ``upgrade`` and ``downgrade`` bodies are each just ``pass``, i.e., two
   ``pass`` lines between the autogen markers. Anything else means alembic
   still sees drift between the migrations and the YAML.

2) **Temporary-Postgres cycle.** Spin up a clean Postgres instance, upgrade
   to ``head-1`` (the pre-migration state), compare against the *old* YAML to
   confirm the migration's starting point matches; upgrade to ``head`` and
   compare against the *new* YAML; downgrade ``-1`` and confirm the diff
   matches the pre-upgrade diff (i.e. ``downgrade`` is a true inverse).

3) **Live-instance cycle (optional).** If ``CONSDB_URL`` is set, run two
   full upgrade-then-downgrade cycles against that instance. This catches
   issues that only appear when migrations run against real data rather than
   an empty test schema.
   NOTE: ``CONSDB_URL`` must point at a local/throwaway Postgres.
   NEVER use this script at BTS, TTS, USDF, or Summit.

Stage (2) needs both a *before* and an *after* copy of the sdm_schemas repo:

  * "after"
      Defaults to ``$SDM_SCHEMAS_DIR`` (default ``$CONSDB_DIR/sdm_schemas``)
  * "before"
      Defaults to ``$CONSDB_DIR/sdm_schemas-old``

Both paths are overridable via CLI flags.

On failure, a ``validate_schema_debug.json`` artifact is written next to the
repo root with normalized diffs and reflected constraint state to make
debugging easier.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from enum import IntEnum
from pathlib import Path

import sqlalchemy as sa
from felis.datamodel import Schema
from felis.metadata import MetaDataBuilder
from felis.tests.postgresql import setup_postgres_test_db
from sqlalchemy.sql import text

from alembic.autogenerate import compare_metadata
from alembic.migration import MigrationContext

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "python"))
from lsst.consdb.cdb_pgsphere import add_shadow_column  # noqa: E402

# Sentinel comments that Alembic emits around the autogenerated body of every
# revision. The no-op check in stage 1 looks for ``pass`` lines *between*
# these markers, ignoring any human-authored code outside them.
AUTOGEN_MARKER_START = "# ### commands auto generated by Alembic - please adjust! ###"
AUTOGEN_MARKER_END = "# ### end Alembic commands ###"


class ExitCode(IntEnum):
    OK = 0
    DIFFS_FOUND = 1


def run(cmd: list[str], *, env: dict[str, str] | None = None) -> None:
    """Run a subprocess command and echo it to stdout."""
    print("+", " ".join(cmd), flush=True)
    sys.stderr.flush()
    subprocess.run(cmd, check=True, env=env)


def _read_autogen_pass_count(path: Path) -> int:
    """Count 'pass' lines in the autogen section of a migration file.

    A no-op autogenerated migration has exactly two ``pass`` lines between
    the autogen markers - one each for ``upgrade()`` and ``downgrade()``.
    Any other count signals that alembic still detects drift between the
    head migration and the target YAML.
    """
    in_block = False
    count = 0
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if stripped == AUTOGEN_MARKER_START:
            in_block = True
            continue
        if stripped == AUTOGEN_MARKER_END:
            in_block = False
            continue
        if in_block and re.match(r"^\s*pass$", line):
            count += 1
    return count


def _find_new_delete_me(versions_dir: Path, before: set[Path]) -> Path:
    """Locate the newly created delete_me migration file.

    The autogenerate run in stage 1 produces a revision file whose name ends
    in ``_delete_me.py`` (matching the revision message we pass). Comparing
    the directory listing before and after the run gives us the new file
    deterministically, even if stale ``_delete_me`` artifacts from a prior
    aborted run still exist.
    """
    after = {path for path in versions_dir.glob("*_delete_me.py")}
    new_files = after - before
    if len(new_files) != 1:
        new_names = ", ".join(sorted(p.name for p in new_files))
        raise RuntimeError(f"Expected exactly one new delete_me file, found {len(new_files)}: {new_names}")
    return new_files.pop()


def _load_metadata(yaml_path: Path) -> sa.MetaData:
    """Build SQLAlchemy metadata from a Felis YAML schema.

    Felis builds a stock SQLAlchemy ``MetaData``; ``add_shadow_column``
    layers on the pgs_region column that the consdb migrations add but
    Felis doesn't know about. Without this, alembic's diff would report
    pgs_region as missing on every comparison.
    """
    schema = Schema.from_uri(yaml_path, context={"id_generation": True})
    metadata = MetaDataBuilder(schema).build()
    add_shadow_column(metadata)
    return metadata


def _include_name(schema_name: str):
    """Create a name filter to scope Alembic comparisons to one schema.

    Without this, ``compare_metadata`` would also visit the ``cdb`` and
    ``public`` schemas and report them as "missing from the target metadata."
    """

    def include_name(name: str, type_: str, parent_names: dict[str, str]) -> bool:
        if type_ == "schema":
            return name == schema_name
        return True

    return include_name


def _include_object(object_, name: str, type_: str, reflected: bool, compare_to) -> bool:
    """Exclude legacy visit1/ccdvisit1 views from Alembic schema comparisons.

    ``visit1`` and ``ccdvisit1`` are created as SQL views by the migrations
    but don't exist as tables in the Felis YAML. Reflection sees them as
    tables; the comparison would flag them as "extra" forever. Filtering
    them out here lets the rest of the comparison stay strict.
    """
    if type_ == "table" and name in {"ccdvisit1", "visit1"}:
        return False
    return True


def _compare_schema(connection: sa.engine.Connection, metadata: sa.MetaData, schema_name: str) -> list:
    """Compare a live schema against expected metadata.

    Returns alembic's diff list - each entry describes one detected
    divergence (added/removed table, column type mismatch, etc.). Empty
    list means the live schema and the target metadata agree.
    """
    # ``compare_type`` and ``compare_server_default`` are off by default in
    # alembic; turning them on makes column-type and server-default changes
    # surface as diffs. ``include_schemas`` widens the walk to every schema
    # in the database, and the include_name / include_object filters then
    # narrow it back to the one instrument schema (minus the visit1/ccdvisit1
    # views). Together these turn the comparison into a strict check.
    context = MigrationContext.configure(
        connection,
        opts={
            "compare_type": True,
            "compare_server_default": True,
            "include_schemas": True,
            "include_name": _include_name(schema_name),
            "include_object": _include_object,
            "target_metadata": metadata,
        },
    )
    return compare_metadata(context, metadata)


def _normalize_diffs(diffs: list) -> list[str]:
    """Return a stable, comparable representation of Alembic diffs.

    ``compare_metadata`` returns structures containing SQLAlchemy objects
    whose repr includes memory addresses (e.g. ``<Column object at 0x...>``
    or ``<sqlalchemy.sql.base.ReadOnlyColumnCollection object at 0x...>``
    embedded in ``ForeignKeyConstraint.__repr__``). Two semantically-equal
    diffs from different Postgres connections would therefore not compare
    equal as Python objects. Normalizing each entry - replacing ``Column``,
    ``DefaultClause``, and constraint instances with structural tuples and
    sorting collections - gives a stable string form that can be compared
    across runs, which the pre-upgrade vs. post-downgrade equality check
    in stage 2 relies on.
    """

    def _col_key(column):
        table_name = column.table.name if column.table is not None else None
        return ("Column", table_name, column.name)

    def normalize(value):
        if isinstance(value, dict):
            return {key: normalize(val) for key, val in sorted(value.items())}
        if isinstance(value, (list, tuple)):
            normalized = [normalize(item) for item in value]
            return tuple(normalized) if isinstance(value, tuple) else normalized
        if isinstance(value, sa.schema.DefaultClause):
            arg = value.arg
            if hasattr(arg, "text"):
                arg = arg.text
            else:
                arg = str(arg)
            return ("DefaultClause", arg, bool(getattr(value, "for_update", False)))
        if isinstance(value, sa.Column):
            return _col_key(value)
        if isinstance(value, sa.ForeignKeyConstraint):
            local = tuple(_col_key(col) for col in value.columns)
            target = tuple(elem.target_fullname for elem in value.elements)
            return ("ForeignKeyConstraint", value.name, local, target)
        if isinstance(value, sa.UniqueConstraint):
            cols = tuple(_col_key(col) for col in value.columns)
            return ("UniqueConstraint", value.name, cols)
        if isinstance(value, sa.PrimaryKeyConstraint):
            cols = tuple(_col_key(col) for col in value.columns)
            return ("PrimaryKeyConstraint", value.name, cols)
        if isinstance(value, sa.CheckConstraint):
            return ("CheckConstraint", value.name, str(value.sqltext))
        return value

    return sorted(repr(normalize(diff)) for diff in diffs)


def _serialize_reflected_schema(connection: sa.engine.Connection, schema_name: str) -> dict[str, object]:
    """Serialize reflected constraint state for debugging.

    When the script fails, the resulting JSON artifact lets a human inspect
    primary keys, unique constraints, and foreign keys as Postgres actually
    sees them - not as alembic interprets them. Sorted output keeps the
    artifact diff-friendly across runs.
    """
    inspector = sa.inspect(connection)
    tables = sorted(inspector.get_table_names(schema=schema_name))
    reflected: dict[str, object] = {}
    for table in tables:
        reflected[table] = {
            "primary_key": inspector.get_pk_constraint(table, schema=schema_name),
            "unique_constraints": sorted(
                inspector.get_unique_constraints(table, schema=schema_name),
                key=lambda item: item.get("name") or "",
            ),
            "foreign_keys": sorted(
                inspector.get_foreign_keys(table, schema=schema_name),
                key=lambda item: item.get("name") or "",
            ),
        }
    return reflected


def main() -> int:
    """CLI entry point for migration validation."""
    parser = argparse.ArgumentParser(description="Validate ConsDB migrations.")
    parser.add_argument("--instrument", default="latiss", help="Instrument name (default: latiss).")
    parser.add_argument(
        "--sdm-schemas-dir",
        default=os.environ.get("SDM_SCHEMAS_DIR", str(REPO_ROOT / "sdm_schemas")),
        help="Path to sdm_schemas (current).",
    )
    parser.add_argument(
        "--sdm-schemas-old-dir",
        default=str(REPO_ROOT / "sdm_schemas-old"),
        help="Path to sdm_schemas-old (unmodified).",
    )
    parser.add_argument(
        "--keep-delete-me",
        action="store_true",
        help="Keep the autogenerated delete_me migration file.",
    )
    args = parser.parse_args()

    instrument = args.instrument
    sdm_schemas_dir = Path(args.sdm_schemas_dir).resolve()
    sdm_schemas_old_dir = Path(args.sdm_schemas_old_dir).resolve()
    if not sdm_schemas_dir.is_dir():
        raise RuntimeError(f"sdm_schemas dir not found: {sdm_schemas_dir}")
    if not sdm_schemas_old_dir.is_dir():
        raise RuntimeError(f"sdm_schemas-old dir not found: {sdm_schemas_old_dir}")

    versions_dir = REPO_ROOT / "alembic" / instrument / "versions"
    # Snapshot the existing delete_me files so we can identify the new one
    # autogenerate is about to create, even if stale copies are still around.
    before_delete_me = {path for path in versions_dir.glob("*_delete_me.py")}
    if before_delete_me:
        stale = ", ".join(sorted(p.name for p in before_delete_me))
        print(
            f"🟡 WARNING: stale delete_me migrations found in {versions_dir}: {stale}. "
            "Consider removing them before re-running.",
        )

    env = os.environ.copy()
    env["SDM_SCHEMAS_DIR"] = str(sdm_schemas_dir)

    # -----------------------------------------------------------------------
    # Stage 1: autogenerate against the post-migration YAML and verify the
    # resulting revision is empty (two `pass` lines). Any other shape means
    # alembic still sees drift between the head migration and the YAML.
    # -----------------------------------------------------------------------
    run(
        [
            sys.executable,
            str(REPO_ROOT / "alembic-autogenerate.py"),
            "--instrument",
            instrument,
            "delete me",
        ],
        env=env,
    )
    delete_me_path = _find_new_delete_me(versions_dir, before_delete_me)
    pass_count = _read_autogen_pass_count(delete_me_path)
    if pass_count != 2:
        print("🔴 Additional migration was not a no-op.")
        raise RuntimeError(f"Expected exactly 2 pass lines in {delete_me_path.name}, found {pass_count}")
    else:
        print("🟢 Additional migration was a no-op.")
    if not args.keep_delete_me:
        delete_me_path.unlink()

    schema_name = f"cdb_{instrument}"
    old_yaml_path = sdm_schemas_old_dir / "yml" / f"{schema_name}.yaml"
    new_yaml_path = sdm_schemas_dir / "yml" / f"{schema_name}.yaml"
    if not old_yaml_path.is_file():
        raise RuntimeError(f"Old YAML not found: {old_yaml_path}")
    if not new_yaml_path.is_file():
        raise RuntimeError(f"New YAML not found: {new_yaml_path}")

    # Reference metadata for the two endpoints of the migration: ``metadata``
    # is what the database should look like before head, ``new_metadata`` is
    # what it should look like at head.
    metadata = _load_metadata(old_yaml_path)
    new_metadata = _load_metadata(new_yaml_path)
    debug_path = REPO_ROOT / "validate_schema_debug.json"
    debug_data: dict[str, object] = {
        "instrument": instrument,
        "schema_name": schema_name,
        "old_yaml_path": str(old_yaml_path),
        "new_yaml_path": str(new_yaml_path),
    }

    # -----------------------------------------------------------------------
    # Stage 2: temporary-Postgres upgrade/downgrade cycle.
    # -----------------------------------------------------------------------
    with setup_postgres_test_db() as instance:
        # Mirror the production setup the alembic migrations expect: the
        # pg_sphere extension, the bookkeeping ``cdb`` schema, the instrument
        # schema, and the ``usdf``/``oods`` roles referenced by GRANTs.
        with instance.engine.begin() as connection:
            connection.execute(text("CREATE EXTENSION IF NOT EXISTS pg_sphere;"))
            connection.execute(text("CREATE SCHEMA cdb;"))
            connection.execute(text(f"CREATE SCHEMA {schema_name};"))
            connection.execute(text("CREATE USER usdf;"))
            connection.execute(text("CREATE USER oods;"))

        temp_env = env.copy()
        temp_env["CONSDB_URL"] = instance.url

        # Bring the DB to the revision *before* head and confirm it lines up
        # with the old YAML. Any diff captured here is the "expected" baseline
        # for the downgrade-equality check further down. This ensures that an
        # alembic downgrade is the inverse operation of the upgrade.
        run(
            ["alembic", "-c", str(REPO_ROOT / "alembic.ini"), "-n", instrument, "upgrade", "head-1"],
            env=temp_env,
        )

        with instance.engine.connect() as connection:
            pre_diffs = _compare_schema(connection, metadata, schema_name)
            debug_data["pre_upgrade"] = {
                "normalized_diffs": _normalize_diffs(pre_diffs),
                "reflected_schema": _serialize_reflected_schema(connection, schema_name),
            }
        normalized_pre_diffs = _normalize_diffs(pre_diffs)
        if pre_diffs:
            print("🟡 Schema differences at pre-upgrade state (vs old YAML):")
            for diff in pre_diffs:
                print(diff)
        else:
            print("🟢 Pre-upgrade schema consistent with old YAML")

        # Upgrade to head and require zero divergence from the new YAML.
        # This is the strictest check in the script -- anything that survives
        # here is a real bug in the head migration.
        run(
            ["alembic", "-c", str(REPO_ROOT / "alembic.ini"), "-n", instrument, "upgrade", "head"],
            env=temp_env,
        )
        with instance.engine.connect() as connection:
            diffs = _compare_schema(connection, new_metadata, schema_name)
            debug_data["post_upgrade"] = {
                "normalized_diffs": _normalize_diffs(diffs),
                "reflected_schema": _serialize_reflected_schema(connection, schema_name),
            }
        if diffs:
            print("🔴 Schema differences found after upgrade:")
            for diff in diffs:
                print(diff)
            debug_path.write_text(json.dumps(debug_data, indent=2, sort_keys=True) + "\n")
            print(f"🟡 Wrote debug artifact: {debug_path}")
            return ExitCode.DIFFS_FOUND
        else:
            print("🟢 Schema consistent after upgrade")

        # Downgrade once and require the resulting diff to match the
        # pre-upgrade baseline. If downgrade is a true inverse of upgrade
        # the two diff lists are identical; otherwise we've discovered a
        # downgrade bug. The diff list, not the empty set, is the right
        # comparison target because the old YAML itself may differ from
        # head-1 in ways unrelated to this migration.
        run(
            ["alembic", "-c", str(REPO_ROOT / "alembic.ini"), "-n", instrument, "downgrade", "-1"],
            env=temp_env,
        )

        with instance.engine.connect() as connection:
            post_diffs = _compare_schema(connection, metadata, schema_name)
            debug_data["post_downgrade"] = {
                "normalized_diffs": _normalize_diffs(post_diffs),
                "reflected_schema": _serialize_reflected_schema(connection, schema_name),
            }
        normalized_post_diffs = _normalize_diffs(post_diffs)
        debug_path.write_text(json.dumps(debug_data, indent=2, sort_keys=True) + "\n")
        print(f"🟡 Wrote debug artifact: {debug_path}")
        if normalized_pre_diffs != normalized_post_diffs:
            print("🔴 Schema differences changed after downgrade:")
            print("pre_diffs:")
            for diff in normalized_pre_diffs:
                print(diff)
            print("post_diffs:")
            for diff in normalized_post_diffs:
                print(diff)
            return ExitCode.DIFFS_FOUND
        else:
            print("🟢 Schema consistent after downgrade")

    # -----------------------------------------------------------------------
    # Stage 3: optional live-instance cycles. Two upgrade-then-downgrade
    # round trips catch issues that only surface against real data, e.g., a
    # migration that's idempotent on an empty schema but not on a populated
    # one.
    # -----------------------------------------------------------------------
    consdb_url = os.environ.get("CONSDB_URL")
    if not consdb_url:
        print("🟡 WARNING: CONSDB_URL not set. Skipping test on live postgresql instance.")
    else:
        live_env = env.copy()
        live_env["CONSDB_URL"] = consdb_url
        for cycle in range(1, 3):
            print(f"Cycle {cycle}: upgrade -> downgrade")
            run(
                ["alembic", "-c", str(REPO_ROOT / "alembic.ini"), "-n", instrument, "upgrade", "head"],
                env=live_env,
            )
            with sa.create_engine(consdb_url).connect() as connection:
                live_diffs = _compare_schema(connection, new_metadata, schema_name)
            if live_diffs:
                print(f"🔴 Live schema differences found after upgrade in cycle {cycle}:")
                for diff in live_diffs:
                    print(diff)
                return ExitCode.DIFFS_FOUND
            else:
                print(f"🟢 Live schema consistent after upgrade in cycle {cycle}")
            run(
                ["alembic", "-c", str(REPO_ROOT / "alembic.ini"), "-n", instrument, "downgrade", "-1"],
                env=live_env,
            )

    print("🟢 --- All checks passed. ---")
    return ExitCode.OK


if __name__ == "__main__":
    raise SystemExit(main())
