"""Add temperature TMA truss

Revision ID: 16ba20e74d5d
Revises: f0e8602d7819
Create Date: 2026-01-28 18:17:29.503282+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "16ba20e74d5d"
down_revision: Union[str, None] = "f0e8602d7819"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exposure_efd",
        sa.Column(
            "truss_temp_plus_x_plus_y",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Temperature of the TMA truss at the plus X position and plus Y structure position",
        ),
        schema="efd_lsstcam",
    )
    op.add_column(
        "exposure_efd",
        sa.Column(
            "truss_temp_minus_x_minus_y",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Temperature of the TMA truss at the minus X minus Y structure position",
        ),
        schema="efd_lsstcam",
    )
    op.add_column(
        "visit1_efd",
        sa.Column(
            "truss_temp_plus_x_plus_y",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Temperature of the TMA truss at the plus X position and plus Y structure position",
        ),
        schema="efd_lsstcam",
    )
    op.add_column(
        "visit1_efd",
        sa.Column(
            "truss_temp_minus_x_minus_y",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Temperature of the TMA truss at the minus X minus Y structure position",
        ),
        schema="efd_lsstcam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visit1_efd", "truss_temp_minus_x_minus_y", schema="efd_lsstcam")
    op.drop_column("visit1_efd", "truss_temp_plus_x_plus_y", schema="efd_lsstcam")
    op.drop_column("exposure_efd", "truss_temp_minus_x_minus_y", schema="efd_lsstcam")
    op.drop_column("exposure_efd", "truss_temp_plus_x_plus_y", schema="efd_lsstcam")
    # ### end Alembic commands ###
