"""Add higher moment PSF shape information

Revision ID: 95626bd65229
Revises: 9db9c1e9e8d3
Create Date: 2026-04-06 22:33:41.198479+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "95626bd65229"
down_revision: Union[str, None] = "9db9c1e9e8d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "coma_1",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Coma-like higher-order moment combination, M30 + M12.",
        ),
        schema="cdb_lsstcam",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "coma_2",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Coma-like higher-order moment combination, M21 + M03.",
        ),
        schema="cdb_lsstcam",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "trefoil_1",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Trefoil-like higher-order moment combination, M30 - 3*M12.",
        ),
        schema="cdb_lsstcam",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "trefoil_2",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Trefoil-like higher-order moment combination, 3*M21 - M03.",
        ),
        schema="cdb_lsstcam",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "kurtosis",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Kurtosis-like higher-order moment combination, M40 + 2*M22 + M04.",
        ),
        schema="cdb_lsstcam",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "e4_1",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Fourth-order ellipticity-like higher-order moment combination, M40 - M04.",
        ),
        schema="cdb_lsstcam",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "e4_2",
            sa.FLOAT().with_variant(mysql.FLOAT(), "mysql").with_variant(sa.FLOAT(), "postgresql"),
            nullable=True,
            comment="Fourth-order ellipticity-like higher-order moment combination, 2*(M31 + M13).",
        ),
        schema="cdb_lsstcam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ccdvisit1_quicklook", "e4_2", schema="cdb_lsstcam")
    op.drop_column("ccdvisit1_quicklook", "e4_1", schema="cdb_lsstcam")
    op.drop_column("ccdvisit1_quicklook", "kurtosis", schema="cdb_lsstcam")
    op.drop_column("ccdvisit1_quicklook", "trefoil_2", schema="cdb_lsstcam")
    op.drop_column("ccdvisit1_quicklook", "trefoil_1", schema="cdb_lsstcam")
    op.drop_column("ccdvisit1_quicklook", "coma_2", schema="cdb_lsstcam")
    op.drop_column("ccdvisit1_quicklook", "coma_1", schema="cdb_lsstcam")
    # ### end Alembic commands ###
