FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/opt/consdb/python

RUN pip install --no-cache-dir sqlalchemy psycopg2-binary

WORKDIR /opt/consdb

COPY python/lsst/consdb/__init__.py python/lsst/consdb/__init__.py
COPY python/lsst/consdb/consistency_queries.py python/lsst/consdb/consistency_queries.py
COPY python/lsst/consdb/daily_consistency_check.py python/lsst/consdb/daily_consistency_check.py

# Required environment variables:
#   DB_HOST
#   DB_PASS
#   DB_USER
#   DB_NAME
# Optional environment variables:
#   DB_PORT
#   DAY_OBS
#   INSTRUMENTS

ENTRYPOINT ["python", "-m", "lsst.consdb.daily_consistency_check"]
