"""Add column scheduler_note to exposure

Revision ID: 28c1d06f768d
Revises: 99ff646cd4b0
Create Date: 2025-05-14 16:05:04.067939+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "28c1d06f768d"
down_revision: Union[str, None] = "99ff646cd4b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exposure",
        sa.Column(
            "scheduler_note",
            sa.VARCHAR(length=1024)
            .with_variant(mysql.VARCHAR(length=1024), "mysql")
            .with_variant(sa.VARCHAR(length=1024), "postgresql"),
            nullable=True,
            comment="A note indicating how or why the observation was chosen by the Feature Based Scheduler.",
        ),
        schema="cdb_latiss",
    )

    op.execute("DROP VIEW cdb_latiss.ccdvisit1")
    op.execute("DROP VIEW cdb_latiss.visit1")
    op.execute("CREATE VIEW cdb_latiss.ccdvisit1 AS SELECT * FROM cdb_latiss.ccdexposure")
    op.execute("CREATE VIEW cdb_latiss.visit1 AS SELECT * FROM cdb_latiss.exposure")
    op.execute("ALTER TABLE cdb_latiss.ccdvisit1 RENAME COLUMN ccdexposure_id TO ccdvisit_id")
    op.execute("ALTER TABLE cdb_latiss.ccdvisit1 RENAME COLUMN exposure_id TO visit_id")
    op.execute("ALTER TABLE cdb_latiss.visit1 RENAME COLUMN exposure_id TO visit_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exposure", "scheduler_note", schema="cdb_latiss")

    op.execute("DROP VIEW cdb_latiss.ccdvisit1")
    op.execute("DROP VIEW cdb_latiss.visit1")
    op.execute("CREATE VIEW cdb_latiss.ccdvisit1 AS SELECT * FROM cdb_latiss.ccdexposure")
    op.execute("CREATE VIEW cdb_latiss.visit1 AS SELECT * FROM cdb_latiss.exposure")
    op.execute("ALTER TABLE cdb_latiss.ccdvisit1 RENAME COLUMN ccdexposure_id TO ccdvisit_id")
    op.execute("ALTER TABLE cdb_latiss.ccdvisit1 RENAME COLUMN exposure_id TO visit_id")
    op.execute("ALTER TABLE cdb_latiss.visit1 RENAME COLUMN exposure_id TO visit_id")
    # ### end Alembic commands ###
