"""Remove s_ra and s_dec from ccdvisit1_quicklook

Revision ID: 6286faecb16b
Revises: 68b3d07af9e6
Create Date: 2026-08-17 19:29:05.810456+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6286faecb16b"
down_revision: Union[str, None] = "68b3d07af9e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ccdvisit1_quicklook", "s_ra", schema="cdb_latiss")
    op.drop_column("ccdvisit1_quicklook", "s_dec", schema="cdb_latiss")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "s_dec",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Central Spatial Position in ICRS; Computed declination of CCD center.",
        ),
        schema="cdb_latiss",
    )
    op.add_column(
        "ccdvisit1_quicklook",
        sa.Column(
            "s_ra",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Central Spatial Position in ICRS; Computed right ascension of CCD center.",
        ),
        schema="cdb_latiss",
    )
    # ### end Alembic commands ###
