name: lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install
        run: pip install -r <(curl https://raw.githubusercontent.com/lsst/linting/main/requirements.txt)

      - name: Run linter
        run: flake8
