name: lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-workflow:
    uses: lsst/rubin_workflows/.github/workflows/formatting.yaml@main
    with:
      ruff_version: ">=0.16,<0.17"

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: j178/prek-action@v3.0.0
